/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view.Materia;

import br.com.dao.LocalDaAulaDAO;
import br.com.dao.SemestreDAO;
import br.com.dao.SemestreVigenteDAO;
import br.com.dao.jdbc.LocalDaAulaJDBC;
import br.com.dao.jdbc.SemestreJDBC;
import br.com.dao.jdbc.SemestreVigenteJDBC;
import br.com.data.LocalDaAula;
import br.com.data.Semestre;
import br.com.data.SemestreVigente;
import java.util.List;

/**
 *
 * @author aluno
 */
public class VIEWAdicionarMateria extends javax.swing.JFrame {

    /**
     * Creates new form VIEWAdicionarMateria
     */
    public VIEWAdicionarMateria() {
        initComponents();
        fillAllCombos();
    }

    public void fillAllCombos() {

        SemestreDAO semestreDAO = new SemestreJDBC();
        List<Semestre> Semestres = semestreDAO.read();

        for (Semestre s : Semestres) {
            cboSemestre.addItem(s);
        }

        SemestreVigenteDAO semestreVigenteDAO = new SemestreVigenteJDBC();
        List<SemestreVigente> SemestresVigentes = semestreVigenteDAO.read();

        for (SemestreVigente s : SemestresVigentes) {
            cboSemestreVigente.addItem(s);
        }

        /*SemestreDAO semestreDAO = new SemestreJDBC();
        List<Semestre> Semestres = semestreDAO.read();

        for (Semestre s : Semestres) {
            cboSemestre.addItem(s);
        }*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboSemestreVigente = new javax.swing.JComboBox();
        cboSemestre = new javax.swing.JComboBox();
        cboLocalDaAula = new javax.swing.JComboBox();
        lblSemestre = new javax.swing.JLabel();
        lblSemestreVigente = new javax.swing.JLabel();
        lblLocalDaAula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        cboSemestreVigente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        cboSemestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cboSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSemestreActionPerformed(evt);
            }
        });

        cboLocalDaAula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cboLocalDaAula.setPreferredSize(new java.awt.Dimension(90, 22));

        lblSemestre.setText("Semestre");

        lblSemestreVigente.setText("Semestre vigente");

        lblLocalDaAula.setText("Local da aula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSemestre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboSemestre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboLocalDaAula, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLocalDaAula, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(cboSemestreVigente, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSemestreVigente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLocalDaAula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboLocalDaAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSemestre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(lblSemestreVigente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboSemestreVigente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        setBounds(0, 0, 416, 308);
    }// </editor-fold>//GEN-END:initComponents

    private void cboSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSemestreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VIEWAdicionarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VIEWAdicionarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VIEWAdicionarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VIEWAdicionarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VIEWAdicionarMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboLocalDaAula;
    private javax.swing.JComboBox cboSemestre;
    private javax.swing.JComboBox cboSemestreVigente;
    private javax.swing.JLabel lblLocalDaAula;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JLabel lblSemestreVigente;
    // End of variables declaration//GEN-END:variables
}
