/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view.professor;

import Atxy2k.CustomTextField.RestrictedTextField;
import br.com.dao.ProfessorDAO;
import br.com.dao.ProfessorDAOJDBC;
import br.com.data.Professor;

/**
 *
 * @author Lucas
 */
public final class VIEWInsere extends javax.swing.JFrame {

    /**
     * Creates new form VIEWInsere
     */
    public VIEWInsere() {
        initComponents();
        this.setLocationRelativeTo(null);
        invisibibleContent();

        RestrictedTextField validaMatricula = new RestrictedTextField(txtMatricula);
        validaMatricula.setOnlyNums(true);
        validaMatricula.setLimit(7);

        RestrictedTextField validaNomeProfessor = new RestrictedTextField(txtNomeProfessor);
        validaNomeProfessor.setOnlyText(true);
        validaNomeProfessor.setLimit(50);
        validaNomeProfessor.setAcceptSpace(true);
    }

    public void invisibibleContent() {
        lblDocente.setVisible(false);
        txtNomeProfessor.setVisible(false);
        btnInserir.setVisible(false);
    }

    public void visibleContent() {
        lblDocente.setVisible(true);
        txtNomeProfessor.setVisible(true);
    }

    public void buttonVisible() {
        btnInserir.setVisible(true);
    }

    public void buttonInvisible() {
        btnInserir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatricula = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtNomeProfessor = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();

        setResizable(false);

        lblMatricula.setText("Matrícula");

        lblDocente.setText("Docente");

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        txtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatriculaKeyReleased(evt);
            }
        });

        txtNomeProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeProfessorKeyReleased(evt);
            }
        });

        btnInserir.setText("Enviar");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInserir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblMatricula)
                        .addComponent(lblDocente)
                        .addComponent(txtNomeProfessor)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInserir)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        Professor professor = new Professor();
        ProfessorDAO professorInserido = new ProfessorDAOJDBC();

        professor.setMatricula(txtMatricula.getText());
        professor.setNomeProfessor(txtNomeProfessor.getText());

        professorInserido.create(professor);
        this.setVisible(false);

    }//GEN-LAST:event_btnInserirActionPerformed

    private void txtMatriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaKeyReleased
        if (txtMatricula.getText().length() == 7) {
            visibleContent();
        } else {
            invisibibleContent();
        }
    }//GEN-LAST:event_txtMatriculaKeyReleased

    private void txtNomeProfessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProfessorKeyReleased
        if (txtNomeProfessor.getText().length() > 7) {
            buttonVisible();
        } else {
            buttonInvisible();
        }
    }//GEN-LAST:event_txtNomeProfessorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNomeProfessor;
    // End of variables declaration//GEN-END:variables
}
