package br.com.view.professor;

import br.com.dao.ProfessorDAO;
import br.com.dao.jdbc.ProfessorJDBC;
import br.com.data.Professor;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Lucas
 */
public class VIEWProfessor extends javax.swing.JFrame {

    /**
     * Creates new form VIEWTeste
     */
    Professor professor = new Professor();
    ProfessorDAO pDao = new ProfessorJDBC();

    public VIEWProfessor() {
        initComponents();
        initTable();
        this.setIconImage(new ImageIcon(getClass().getResource("/br/com/icons/Teacher Icon.png")).getImage());
        this.setLocationRelativeTo(null);
        lblProcurar.setIcon(new ImageIcon(getClass().getResource("/br/com/icons/Search.png")));
    }

    public void initTable() {
        DefaultTableCellRenderer rendererCentro = new DefaultTableCellRenderer();
        rendererCentro.setHorizontalAlignment(SwingConstants.CENTER);
        TableColumnModel modeloDaColuna = jTProfessores.getColumnModel();
        DefaultTableModel modelo = (DefaultTableModel) jTProfessores.getModel();
        jTProfessores.setRowSorter(new TableRowSorter(modelo));
        

        modeloDaColuna.getColumn(0).setMaxWidth(35);
        modeloDaColuna.getColumn(0).setCellRenderer(rendererCentro);
        modeloDaColuna.getColumn(0).setHeaderRenderer(rendererCentro);

        modeloDaColuna.getColumn(1).setMinWidth(300);
        modeloDaColuna.getColumn(1).setMaxWidth(350);
        modeloDaColuna.getColumn(1).setHeaderRenderer(rendererCentro);

        modeloDaColuna.getColumn(2).setHeaderRenderer(rendererCentro);
        modeloDaColuna.getColumn(2).setCellRenderer(rendererCentro);
        
        readJTable();
        fillComboProfessor();
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTProfessores.getModel();
        modelo.setNumRows(0);
        ProfessorDAO pDao = new ProfessorJDBC();

        for (Professor p : pDao.read()) {
            modelo.addRow(new Object[]{
                p.getCodigoProfessor(),
                p.getNomeProfessor(),
                p.getMatricula()
            });
        }
    }

    public void searchJTable(Professor prof) {
        DefaultTableModel modelo = (DefaultTableModel) jTProfessores.getModel();
        modelo.setNumRows(0);
        ProfessorDAO pDAO = new ProfessorJDBC();

        for (Professor p : pDAO.search(prof)) {
            modelo.addRow(new Object[]{
                p.getCodigoProfessor(),
                p.getNomeProfessor(),
                p.getMatricula()
            });
        }
    }

    public void fillComboProfessor() {
        ProfessorDAO ProfessorDAO = new ProfessorJDBC();
        List<Professor> Professores = ProfessorDAO.read();

        for (Professor p : Professores) {
            cbxProfessor.addItem(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProfessores = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtBuscarProfessor = new javax.swing.JTextField();
        lblProcurar = new javax.swing.JLabel();
        cbxProfessor = new javax.swing.JComboBox();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta Professores");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setName("Professores IFBA - Camaçari"); // NOI18N
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Docente", "Matricula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProfessores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTProfessoresKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTProfessoresKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTProfessores);

        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtBuscarProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProfessorKeyReleased(evt);
            }
        });

        lblProcurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProcurarMouseClicked(evt);
            }
        });

        cbxProfessor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbxProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(lblProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(cbxProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(cbxProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (jTProfessores.getSelectedRow() != -1) {
            professor.setCodigoProfessor((int) jTProfessores.getValueAt(jTProfessores.getSelectedRow(), 0));
            professor.setNomeProfessor((String) jTProfessores.getValueAt(jTProfessores.getSelectedRow(), 1));
            professor.setMatricula((String) jTProfessores.getValueAt(jTProfessores.getSelectedRow(), 2));
            new VIEWEditarProfessor(professor).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma linha da tabela");
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        new VIEWInsereProfessor().setVisible(true);
        txtBuscarProfessor.setText(null);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void txtBuscarProfessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProfessorKeyReleased

        if (txtBuscarProfessor.getText().length() > 0) {
            professor.setNomeProfessor(txtBuscarProfessor.getText());
            pDao.search(professor);
            searchJTable(professor);
        } else {
            readJTable();
        }

    }//GEN-LAST:event_txtBuscarProfessorKeyReleased

    private void lblProcurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProcurarMouseClicked

    }//GEN-LAST:event_lblProcurarMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        readJTable();
        fillComboProfessor();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jTProfessoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProfessoresKeyReleased
        
    }//GEN-LAST:event_jTProfessoresKeyReleased

    private void jTProfessoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProfessoresKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTProfessoresKeyPressed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (jTProfessores.getSelectedRow() != -1) {
            professor.setCodigoProfessor((int) jTProfessores.getValueAt(jTProfessores.getSelectedRow(), 0));
            professor.setNomeProfessor((String) jTProfessores.getValueAt(jTProfessores.getSelectedRow(), 1));
            professor.setMatricula((String) jTProfessores.getValueAt(jTProfessores.getSelectedRow(), 2));
            pDao.delete(professor);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma linha da tabela");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        jTProfessores.clearSelection();
    }//GEN-LAST:event_formMouseClicked

    private void cbxProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VIEWProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VIEWProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VIEWProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VIEWProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VIEWProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox cbxProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTProfessores;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblProcurar;
    private javax.swing.JTextField txtBuscarProfessor;
    // End of variables declaration//GEN-END:variables
}
