/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view.localdaaula;

import Atxy2k.CustomTextField.RestrictedTextField;
import br.com.dao.LocalDaAulaDAO;
import br.com.dao.jdbc.LocalDaAulaJDBC;
import br.com.data.LocalDaAula;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author Lucas
 */
public final class VIEWInsereLocalDaAula extends javax.swing.JFrame {

    LocalDaAula local = new LocalDaAula();
    LocalDaAulaDAO localInserido = new LocalDaAulaJDBC();

    /**
     * Creates new form VIEWInsere
     */
    public VIEWInsereLocalDaAula() {
        initComponents();
        this.setLocationRelativeTo(null);

        RestrictedTextField validaHorario = new RestrictedTextField(txtLocalDaAula);
        validaHorario.setLimit(15);
        validaHorario.setAcceptSpace(true);
    }

    public void buttonVisible() {
        btnInserir.setVisible(true);
    }

    public void buttonInvisible() {
        btnInserir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHorario = new javax.swing.JLabel();
        txtLocalDaAula = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();

        setResizable(false);

        lblHorario.setText("Local da Aula");

        txtLocalDaAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalDaAulaActionPerformed(evt);
            }
        });
        txtLocalDaAula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLocalDaAulaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLocalDaAulaKeyReleased(evt);
            }
        });

        btnInserir.setText("Enviar");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLocalDaAula, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHorario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnInserir)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLocalDaAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnInserir)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLocalDaAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalDaAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalDaAulaActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        local.setLocalDaAula(txtLocalDaAula.getText());
        localInserido.create(local);
        this.setVisible(false);

    }//GEN-LAST:event_btnInserirActionPerformed

    private void txtLocalDaAulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocalDaAulaKeyReleased
    }//GEN-LAST:event_txtLocalDaAulaKeyReleased

    private void txtLocalDaAulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocalDaAulaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            local.setLocalDaAula(txtLocalDaAula.getText());
            localInserido.create(local);
            this.setVisible(false);
        }
    }//GEN-LAST:event_txtLocalDaAulaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JTextField txtLocalDaAula;
    // End of variables declaration//GEN-END:variables
}
